apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - userservice.yaml
components:
  - ../../../components/base/common
  - ../../../components/base/python-pod
patches:
  - target:
      kind: Deployment
    path: add-private-key-volume.yaml