apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - userservice.yaml
components:
  - ../../../k8s/base/common-python-pod
patches:
  - target:
      kind: Deployment
    path: add-private-key-volume.yaml