apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
spec:
  patches:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: resource-group-controller-manager
      namespace: resource-group-system
    spec:
      template:
        spec:
          containers:
          - name: manager
            resources:
              requests:
                memory: "200Mi"
              limits:
                memory: "1Gi"