apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
namespace: bank-of-anthos-development
commonLabels:
  environment: development
components:
  - ../../base/common
  - ../../base/istio-proxy-hold-application-patch
