apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - path: proxy.yaml
    target:
      kind: Deployment
  - path: ledger-db.yaml
    target:
      kind: ConfigMap
      name: ledger-db-config
  - path: accounts-db.yaml
    target:
      kind: ConfigMap
      name: accounts-db-config

