apiVersion: skaffold/v2beta26
kind: Config
metadata: 
  name: ledgerwriter
requires:
  - configs: [ledger-db]
    path: ../ledger-db/skaffold.yaml
build:
  artifacts:
    - image: ledgerwriter
      context: ../../../
      jib:
        project: src/ledger/ledgerwriter
deploy:
  kubectl:
    manifests:
      - k8s/ledgerwriter.yaml