apiVersion: skaffold/v2beta26
kind: Config
metadata: 
  name: ledgerwriter
requires:
  - configs: [ledger-db]
    path: ../ledger-db/skaffold.yaml
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: ledgerwriter
      context: ../../../
      jib:
        project: src/ledger/ledgerwriter
profiles:
  - name: development
    activation:
      - command: dev
    deploy:
      kustomize:
        paths: ["k8s/development"]
  - name: staging
    deploy:
      kustomize:
        paths: ["k8s/staging"]
  - name: production
    deploy:
      kustomize:
        paths: ["k8s/production"]