apiVersion: skaffold/v2beta26
kind: Config
metadata: 
  name: ledger-db
requires:
  - configs: [config]
    path: ../../shared/config/skaffold.yaml
build:
  artifacts:
    - image: ledger-db
      context: .
deploy:
  kubectl:
    manifests:
      - k8s/ledger-db.yaml