apiVersion: skaffold/v2beta26
kind: Config
metadata: 
  name: ledger-db
profiles:
  - name: development
    activation:
      - command: dev
    deploy:
      kustomize:
        paths: ["k8s/development"]
    build:
      tagPolicy:
        sha256: {}
      artifacts:
        - image: ledger-db
          context: .