apiVersion: skaffold/v2beta26
kind: Config
metadata: 
  name: ledger-db
build:
  artifacts:
    - image: ledger-db
      context: .
deploy:
  kustomize:
    paths: ["k8s/base"]
profiles:
  - name: development
    deploy:
      kustomize:
        paths: ["k8s/development"]
  - name: staging
    deploy:
      kustomize:
        paths: ["k8s/staging"]
  - name: production
    deploy:
      kustomize:
        paths: ["k8s/production"]
