steps:
  - name: gcr.io/cloud-builders/gsutil
    args: ['cp', $_CACHE_URI, '/workspace/cache'] # always write skaffold cache to filename cache in workspace
  - name: gcr.io/k8s-skaffold/skaffold:v2.0.0
    args:
      - "/workspace/mvnw"
      - "jib:_skaffold-fail-if-jib-out-of-date"
      - "-Djib.requiredVersion=1.4.0"
      - "--projects"
      - "src/ledger/balancereader"
      - "--also-make"
      - "jib:_skaffold-files-v2"      
      - "--batch-mode"
    env:
      - "MAVEN_USER_HOME=/workspace/.m2"
  - name: gcr.io/k8s-skaffold/skaffold:v2.0.0
    args:
      - "skaffold"
      - "build"
      - "--file-output=/workspace/artifacts.json"
      - "--default-repo=$_CONTAINER_REGISTRY"
      - "--cache-file=/workspace/$_CACHE" # set _CACHE to anything other than "cache" e.g. "no-cache" to reset skaffold cache
      - "--filename=src/$_TEAM/skaffold.yaml"
    env:
      - "MAVEN_USER_HOME=/workspace/.m2"
  - name: gcr.io/cloud-builders/gsutil
    args: ['cp', '/workspace/$_CACHE',  $_CACHE_URI]
  - name: gcr.io/cloud-builders/gcloud
    args: 
      - "deploy"
      - "releases"
      - "create"
      - "$_TEAM-$SHORT_SHA-$$DATE-$$TIME"
      - "--delivery-pipeline=$_TEAM"
      - "--build-artifacts=/workspace/artifacts.json"
      - "--skaffold-file=src/$_TEAM/skaffold.yaml"
      - "--region=europe-west1"
      - "--gcs-source-staging-dir=$_SOURCE_STAGING_BUCKET/$SHORT_SHA"
      - "--skaffold-version=skaffold_preview"
options:
  logging: CLOUD_LOGGING_ONLY