apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bank-of-anthos-staging
resources:
  - ../../../base
  - namespace.yaml
patches:
- target:
    kind: ServiceAccount
  patch: |-
    - op: add
      path: /metadata/annotations/iam.gke.io~1gcp-service-account
      value: gke-workload-staging@boa-tf-max-2g.iam.gserviceaccount.com 
# TODO: how to inject projectId here?