apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
- target:
    kind: ServiceAccount
  patch: |-
    - op: add
      path: /metadata/annotations/iam.gke.io~1gcp-service-account
      value: gke-workload-development@boa-tf-1.iam.gserviceaccount.com 
# how to inject projectId here?