apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - contacts.yaml
components:
  - ../../../k8s/base/common
  - ../../../k8s/base/python-pod
  - ../../../../k8s/base/add-public-key-volume
