apiVersion: skaffold/v2beta26
kind: Config
metadata: 
  name: transactionhistory
requires:
  - configs: [ledger-db]
    path: ../ledger-db/skaffold.yaml
build:
  artifacts:
    - image: transactionhistory
      jib:
        project: :transactionhistory
deploy:
  kubectl:
    manifests:
      - k8s/transactionhistory.yaml