apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - populate-job.yaml
components:
  - ../../../../components/base/common
  - ../../../../components/staging/common