apiVersion: skaffold/v3
kind: Config
metadata:
  name: userservice
requires:
- configs:
  - accounts-db
  path: ../accounts-db/skaffold.yaml
build:
  artifacts:
  - image: userservice
    context: .
  tagPolicy:
    sha256: {}
profiles:
- name: development
  activation:
  - command: dev
  manifests:
    kustomize:
      paths:
      - k8s/overlays/development
- name: staging
  manifests:
    kustomize:
      paths:
      - k8s/overlays/staging
- name: production
  manifests:
    kustomize:
      paths:
      - k8s/overlays/production
