apiVersion: skaffold/v3
kind: Config
metadata:
  name: userservice
requires:
- configs:
  - accounts-db
  path: ../accounts-db/skaffold.yaml
build:
  artifacts:
  - image: userservice
    context: .
  tagPolicy:
    sha256: {}
test:
  - image: userservice # code style
    context: .
    custom:
      - command: |
          pylint --rcfile=../../../.pylintrc *.py
        timeoutSeconds: 1200
        dependencies: 
          paths:
            - "**/*.py"
            - "../../../.pylintrc"
  - image: userservice # unit tests
    context: .
    custom:
      - command: |
          python3 -m venv $HOME/venv-userservice
          source $HOME/venv-userservice/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          python -m pytest -v -p no:warnings
        timeoutSeconds: 1200
        dependencies: 
          paths:
            - "**/*.py"
            - "requirements.txt"
  - image: userservice # code coverage
    context: .
    custom:
      - command: |
          python3 -m venv $HOME/venv-userservice
          source $HOME/venv-userservice/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          python -m pytest --cov=./ tests/
        timeoutSeconds: 1200
        dependencies: 
          paths:
            - "**/*.py"
            - "requirements.txt"
deploy:
  kubectl: {}
profiles:
- name: development
  activation:
  - command: dev
  manifests:
    kustomize:
      paths:
      - k8s/overlays/development
- name: staging
  manifests:
    kustomize:
      paths:
      - k8s/overlays/staging
- name: production
  manifests:
    kustomize:
      paths:
      - k8s/overlays/production
