apiVersion: skaffold/v2beta26
kind: Config
metadata: 
  name: userservice
requires:
  - configs: [accounts-db]
    path: ../accounts-db/skaffold.yaml
build:
  artifacts:
    - image: userservice
      context: .
deploy:
  kustomize:
    paths: ["k8s/base"]
profiles:
  - name: development
    deploy:
      kustomize:
        paths: ["k8s/development"]
  - name: staging
    deploy:
      kustomize:
        paths: ["k8s/staging"]
  - name: production
    deploy:
      kustomize:
        paths: ["k8s/production"]