apiVersion: skaffold/v2beta26
kind: Config
metadata: 
  name: frontend
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: frontend
      context: .
deploy:
  kustomize:
    paths: ["k8s/base"]
profiles:
  - name: development
    activation:
      - command: dev
    deploy:
      kustomize:
        paths: ["k8s/development"]
  - name: staging
    deploy:
      kustomize:
        paths: ["k8s/staging"]
  - name: production
    deploy:
      kustomize:
        paths: ["k8s/production"]