apiVersion: skaffold/v3
kind: Config
metadata:
  name: frontend
build:
  artifacts:
  - image: frontend
    context: .
    sync:
      infer:
      - '**/*.py'
      - logging.conf
      - static/**
      - templates/*.html
  tagPolicy:
    sha256: {}
profiles:
- name: development
  activation:
  - command: dev
  manifests:
    kustomize:
      paths:
      - k8s/overlays/development
- name: staging
  manifests:
    kustomize:
      paths:
      - k8s/overlays/staging
  deploy:
    statusCheck: false
- name: production
  manifests:
    kustomize:
      paths:
      - k8s/overlays/production
  deploy:
    statusCheck: false
