apiVersion: skaffold/v2beta26
kind: Config
metadata: 
  name: frontend
build:
  artifacts:
    - image: frontend
      context: .
profiles:
  - name: staging
    deploy:
      kustomize:
        paths: ["k8s/staging"]
  - name: production
    deploy:
      kustomize:
        paths: ["k8s/production"]