apiVersion: skaffold/v2beta26
kind: Config
metadata: 
  name: accounts-db
requires:
  - configs: [config]
    path: ../../shared/config/skaffold.yaml
build:
  artifacts:
    - image: accounts-db
      context: .
profiles:
  - name: staging
    deploy:
      kustomize:
        paths: ["k8s/staging"]
  - name: production
    deploy:
      kustomize:
        paths: ["k8s/production"]