apiVersion: skaffold/v2beta26
kind: Config
metadata: 
  name: accounts-db
profiles:
  - name: development
    activation:
      - command: dev
    deploy:
      kustomize:
        paths: ["k8s/development"]
    build:
      artifacts:
        - image: accounts-db
          context: .

