apiVersion: skaffold/v2beta26
kind: Config
metadata: 
  name: balancereader
requires:
  - configs: [ledger-db]
    path: ../ledger-db/skaffold.yaml
build:
  artifacts:
    - image: balancereader
      jib:
        project: :balancereader
deploy:
  kubectl:
    manifests:
      - k8s/balancereader.yaml