apiVersion: skaffold/v3
kind: Config
metadata:
  name: balancereader
requires:
- configs:
  - ledger-db
  path: ../ledger-db/skaffold.yaml
build:
  artifacts:
  - image: balancereader
    context: ../../../
    jib:
      project: src/ledger/balancereader
  tagPolicy:
    sha256: {}
profiles:
- name: development
  activation:
  - command: dev
  manifests:
    kustomize:
      paths:
      - k8s/overlays/development
- name: staging
  manifests:
    kustomize:
      paths:
      - k8s/overlays/staging
- name: production
  manifests:
    kustomize:
      paths:
      - k8s/overlays/production
