apiVersion: skaffold/v3
kind: Config
metadata:
  name: loadgenerator
profiles:
- name: staging
  build:
    artifacts:
    - image: loadgenerator
      context: .
    tagPolicy:
      sha256: {}
  manifests:
    kustomize:
      paths:
      - k8s/overlays/staging
  deploy:
    statusCheck: false
    kubectl: {}
