apiVersion: skaffold/v2beta26
kind: Config
metadata: 
  name: accounts
requires:
  - configs: [contacts]
    path: contacts/skaffold.yaml
  - configs: [userservice]
    path: userservice/skaffold.yaml
profiles:
  - name: staging
    deploy:
      statusCheck: false
  - name: production
    deploy:
      statusCheck: false